### ISSUE TITLE
Django 4.0 support

### ISSUE THREAD

**Issue by MrP01** [nkuttler/django-webmaster-verification#2]
Hello, Django 4.0 has changed the import path for urls away from `django.conf.urls`.

I actively use this app, if needed I could also make a pull request, the main thing important to me is that it will be published on PyPi.

Thank you again.

**Comment by nkuttler** [comment]
Hey, sure, please use a try/except or whatever is necessary to also support Django < 4.

**Comment by MrP01** [comment]
Hello! As it seems, the current version from the repository works already as it has 

```python
from django.urls import re_path
```

as the import statement.

I didn't notice because the latest version in the repository (master or upgrade branch, doesn't matter) is not yet on PyPi.
So maybe you could publish a fresh version '0.4.3'?

I've checked with my projects, the package works perfectly fine with Django 4.0.

**Comment by nkuttler** [comment]
Ah great! Unfortunately right now I don't have an env to run the tests in, travis-ci doesn't seem to have a free plan any more. I'm trying to migrate to azure atm but have no parallel build capability yet. If that's not resolved soon I'll look into moving the tests at least to gitlab.

**Comment by MrP01** [comment]
Travis not being free anymore is cruel.

I saw that you added an azure pipeline integration, as far as I can see it from the logs on azure.com, the command that is being run is `pip install 3.2` for the python 3.8, django 3.2 test, instead of `pip install Django==3.2`. So apparently something about the installation is misconfigured, but I don't know exactly.

**Comment by nkuttler** [comment]
Ah, thanks for finding that! I just checked, apparently I can get a build matrix using github actions too. I think I'll just go with that.

**Comment by nkuttler** [comment]
Package released
